### ISSUE TITLE
crash with Fluidlogged API v2.2.7 when loading ingame 

### ISSUE THREAD

**Issue by hampop** [Red-Studio-Ragnarok/Alfheim#6] opened 2023-09-08 15:12 UTC
## Describe the bug

***A clear and concise description of what the bug is.***

crash with Fluidlogged API v2.2.7 when loading ingame 

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. Go to 'have Fluidlogged API v2.2.7 and load up the game and it will crash '

## Expected behavior

***A clear and concise description of what you expected to happen.***

crash with Fluidlogged API v2.2.7 when loading ingame 

## Screenshots or/and videos

https://github.com/Red-Studio-Ragnarok/Alfheim/assets/87606666/9dfd5013-21a1-4778-8008-c7523276405a

## Logs or/and crash reports

[latest.log](https://github.com/Red-Studio-Ragnarok/Alfheim/files/12561189/latest.log)

## Versions
![image](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/87606666/6fa5d9ac-d0d5-4f14-b512-025d8f43d4c0)

## Specification:

OS: [Windows 11]
CPU: [Ryzen 5 5500u]
GPU: [vega 7]
RAM Allocated: [4gb]

**Comment by Desoroxxx** [comment] 2023-09-08 15:50
Duplicate of #4

**Closed by Desoroxxx** 2023-09-08 15:50 UTC
