### ISSUE TITLE
I can launch the world on modpack but java.lang.NullPointerException

### ISSUE THREAD

**Issue by quentin452** [Red-Studio-Ragnarok/Alfheim#7] opened 2023-09-08 16:25 UTC
## Describe the bug

***A clear and concise description of what the bug is.***

I can launch a world , but after init i got a crash

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.
- [X] I am able only to get the issue in My Modpack
## To Reproduce

***Steps to reproduce the behavior:***

1. Download https://legacy.curseforge.com/minecraft/modpacks/mystics-monstrosity-v6-0-modified-fork
2. Add Alfeim + Update red core + remove phosphor
4. Open the game
5. Open a world
6. crash

## Expected behavior

Don't crash

## Logs or/and crash reports

[latest.log](https://github.com/Red-Studio-Ragnarok/Alfheim/files/12561914/latest.log)

## Versions

- Alfeim: Alfheim-1.0.1
- Forge: 1.12.2 - 14.23.5.2860
- Java: zulu8.70.0.23-ca-jdk8.0.372-linux_x64
- Java JVM: Zulu

## Specification:

- OS: EndeavourOS(Arch linux)
- CPU: I5 10400F
- GPU: RTX 3060
- RAM Allocated: 12GB

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: Processor Base Frequency 2.90 GHz Max Turbo Frequency 4.30 GHz
- CPU Core: 6
- CPU Threads: 12
- RAM Size: 32GB
- RAM Speed: 2666MHZ
- Storage Type: 1TO SSD
- GPU VRAM: 12GB

**Comment by Desoroxxx** [comment] 2023-09-11 15:26
Duplicate of #5

**Closed by Desoroxxx** 2023-09-11 15:26 UTC
